CREATE TABLE ITEM (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    PRIORIDADE BOOLEAN NOT NULL,
    CATEGORIA_ID INTEGER,
    COMPRADO BOOLEAN DEFAULT FALSE,
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID) ON DELETE SET NULL
);
